from __future__ import annotations

"""
IDE-friendly parallel sensitivity runner.

Edit the SETTINGS block below and run this file directly from your IDE.
No CLI arguments are required.

Thesis-focused version:
- runs one-factor and interaction sweeps in parallel
- preserves interaction metadata columns (e.g. theta_3db_deg, Ks_max)
- includes traffic sensitivity and stress-test sweeps
- removes low-value/redundant sensitivity plots
- adds U_mean and minimum feasible prefix / used satellites
- uses median + p10/p90 bands for most continuous metrics
- IMPORTANT: plotting/tables read back the CSV files generated by this script
"""

from dataclasses import replace
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any
import os
import traceback

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from config import ScenarioConfig
from src.pipeline import run_scenario


# =============================================================================
# SETTINGS — edit these directly and press Run in your IDE
# =============================================================================
SETTINGS: dict[str, Any] = {
    # Parallel backend: "process" is recommended for CPU-heavy workloads.
    "backend": "process",             # "process" | "thread"
    "max_workers": max(1, (os.cpu_count() or 4) - 1),

    # Output directory
    "out_dir": "sensitivity_results",

    # Base scenario
    "region_mode": "turkey",         # "turkey" | "debug"
    "constellation_source": "tle",   # "tle" | "walker"
    "tle_path": "starlink.tle",
    "time_utc_iso": None,            # e.g. "2026-01-29T16:19:56Z"
    "enable_plots": False,
    "verbose": False,
    "enable_fastbp_baselines": False,

    # Common sweep axes
    "n_users_list": [1000, 1500, 2000],
    "seeds": [1, 2],

    # One-factor sweeps (baseline-centered)
    "theta_3db_deg_values": [0.9, 1.0, 1.1],
    "elev_mask_deg_values": [20.0, 25.0, 30.0],
    "Ks_max_values": [192, 256, 320],
    "W_slots_values": [6, 8, 10],
    "rho_safe_values": [0.6, 0.7, 0.8],
    # hotspot_scale multiplies both sigma_min and sigma_max
    "hotspot_scale_values": [0.8, 1.0, 1.2],

    # Traffic sensitivity / stress
    "demand_mbps_median_values": [5.0, 10.0, 20.0],
    "demand_mbps_median_stress_values": [10.0, 50.0, 100.0],

    # One interaction study
    "interaction_theta_3db_deg_values": [0.9, 1.0, 1.1],
    "interaction_Ks_max_values": [192, 256, 320],
}


# =============================================================================
# Config / extraction helpers
# =============================================================================

def _deep_replace(obj: Any, updates: dict[str, Any]) -> Any:
    """Nested dataclass replace using dotted keys, e.g. beam.theta_3db_deg."""
    if not updates:
        return obj

    local = {}
    grouped: dict[str, dict[str, Any]] = {}
    for k, v in updates.items():
        if "." in k:
            head, tail = k.split(".", 1)
            grouped.setdefault(head, {})[tail] = v
        else:
            local[k] = v

    kwargs = {}
    for field_name, child_updates in grouped.items():
        child = getattr(obj, field_name)
        kwargs[field_name] = _deep_replace(child, child_updates)
    kwargs.update(local)
    return replace(obj, **kwargs)


def _make_base_cfg() -> ScenarioConfig:
    cfg = ScenarioConfig()
    cfg = replace(
        cfg,
        region_mode=SETTINGS["region_mode"],
        run=replace(
            cfg.run,
            enable_plots=bool(SETTINGS["enable_plots"]),
            verbose=bool(SETTINGS["verbose"]),
            enable_fastbp_baselines=bool(SETTINGS["enable_fastbp_baselines"]),
        ),
        multisat=replace(
            cfg.multisat,
            source=str(SETTINGS["constellation_source"]),
            tle_path=str(SETTINGS["tle_path"]),
            time_utc_iso=SETTINGS["time_utc_iso"],
        ),
    )
    return cfg


def _safe_float(x: Any) -> float:
    try:
        return float(x)
    except Exception:
        return float("nan")


def _extract_main_metrics(res: dict[str, Any]) -> dict[str, Any]:
    main = res.get("main_ref_lb", {}) or {}
    runtime_total = (
        _safe_float(res.get("time_usergen_s", 0.0))
        + _safe_float(res.get("time_sat_select_s", 0.0))
        + _safe_float(res.get("time_assoc_s", 0.0))
        + _safe_float(res.get("time_split_s", 0.0))
        + _safe_float(res.get("time_ent_ref_s", 0.0))
        + _safe_float(res.get("time_lb_ref_s", 0.0))
    )

    best_m = res.get("payload_best_m", res.get("ms_n_active"))
    if best_m is None:
        best_m = res.get("ms_n_active")

    return {
        "payload_feasible": int(bool(res.get("payload_feasible", False))),
        "K": _safe_float(main.get("K")),
        "U_mean": _safe_float(main.get("U_mean")),
        "U_max": _safe_float(main.get("U_max")),
        "ent_edge_pct": _safe_float(main.get("ent_edge_pct")),
        "best_m": _safe_float(best_m),
        "ms_n_active": _safe_float(res.get("ms_n_active")),
        "payload_n_viol_K": _safe_float(res.get("payload_n_viol_K")),
        "payload_n_viol_T": _safe_float(res.get("payload_n_viol_T")),
        "payload_K_over_sum": _safe_float(res.get("payload_K_over_sum")),
        "payload_T_over_sum": _safe_float(res.get("payload_T_over_sum")),
        "runtime_total_s": runtime_total,
    }


# =============================================================================
# Parallel worker
# =============================================================================

def _worker(task: dict[str, Any]) -> dict[str, Any]:
    seed = int(task["seed"])
    n_users = int(task["n_users"])
    updates = dict(task["updates"])
    tag = str(task["tag"])
    x_name = str(task["x_name"])
    x_value = task["x_value"]

    # Preserve extra task metadata such as theta_3db_deg, Ks_max, hotspot_scale, etc.
    meta = {
        k: v
        for k, v in task.items()
        if k not in {"updates", "tag", "x_name", "x_value", "seed", "n_users"}
    }

    cfg = _make_base_cfg()
    cfg = replace(cfg, run=replace(cfg.run, seed=seed, n_users=n_users))
    cfg = _deep_replace(cfg, updates)

    try:
        res = run_scenario(cfg)
        return {
            "ok": 1,
            "tag": tag,
            "x_name": x_name,
            "x_value": x_value,
            "seed": seed,
            "n_users": n_users,
            **meta,
            **updates,
            **_extract_main_metrics(res),
        }
    except Exception as e:
        return {
            "ok": 0,
            "tag": tag,
            "x_name": x_name,
            "x_value": x_value,
            "seed": seed,
            "n_users": n_users,
            **meta,
            **updates,
            "error": f"{type(e).__name__}: {e}",
            "traceback": traceback.format_exc(),
            "payload_feasible": 0,
            "K": float("nan"),
            "U_mean": float("nan"),
            "U_max": float("nan"),
            "ent_edge_pct": float("nan"),
            "best_m": float("nan"),
            "ms_n_active": float("nan"),
            "payload_n_viol_K": float("nan"),
            "payload_n_viol_T": float("nan"),
            "payload_K_over_sum": float("nan"),
            "payload_T_over_sum": float("nan"),
            "runtime_total_s": float("nan"),
        }


def _run_tasks(tasks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    backend = str(SETTINGS["backend"]).lower()
    max_workers = int(SETTINGS["max_workers"])
    Executor = ProcessPoolExecutor if backend == "process" else ThreadPoolExecutor

    results: list[dict[str, Any]] = []
    with Executor(max_workers=max_workers) as ex:
        fut_map = {ex.submit(_worker, t): t for t in tasks}
        for fut in as_completed(fut_map):
            results.append(fut.result())

    results.sort(key=lambda r: (
        str(r.get("tag", "")),
        str(r.get("x_name", "")),
        str(r.get("x_value", "")),
        int(r.get("n_users", 0)),
        int(r.get("seed", 0)),
    ))
    return results


# =============================================================================
# Task builders
# =============================================================================

def _build_one_factor_tasks() -> list[dict[str, Any]]:
    tasks: list[dict[str, Any]] = []
    sweep_defs = [
        ("theta_3db_deg", "beam.theta_3db_deg", SETTINGS["theta_3db_deg_values"]),
        ("elev_mask_deg", "multisat.elev_mask_deg", SETTINGS["elev_mask_deg_values"]),
        ("Ks_max", "payload.Ks_max", SETTINGS["Ks_max_values"]),
        ("W_slots", "payload.W_slots", SETTINGS["W_slots_values"]),
        ("rho_safe", "ent.rho_safe", SETTINGS["rho_safe_values"]),
        ("hotspot_scale", "hotspot_scale", SETTINGS["hotspot_scale_values"]),
        ("demand_mbps_median", "traffic.demand_mbps_median", SETTINGS["demand_mbps_median_values"]),
        ("demand_mbps_median_stress", "traffic.demand_mbps_median", SETTINGS["demand_mbps_median_stress_values"]),
    ]

    for sweep_name, dotted_key, values in sweep_defs:
        for x in values:
            updates = {}
            meta = {}
            if dotted_key == "hotspot_scale":
                base = _make_base_cfg()
                updates["usergen.hotspot_sigma_m_min"] = float(base.usergen.hotspot_sigma_m_min) * float(x)
                updates["usergen.hotspot_sigma_m_max"] = float(base.usergen.hotspot_sigma_m_max) * float(x)
                meta["hotspot_scale"] = x
            else:
                updates[dotted_key] = x
                meta[sweep_name] = x

            for n_users in SETTINGS["n_users_list"]:
                for seed in SETTINGS["seeds"]:
                    tasks.append({
                        "tag": f"one_factor:{sweep_name}",
                        "x_name": sweep_name,
                        "x_value": x,
                        "n_users": n_users,
                        "seed": seed,
                        "updates": updates,
                        **meta,
                    })
    return tasks


def _build_interaction_tasks() -> list[dict[str, Any]]:
    tasks: list[dict[str, Any]] = []
    for theta in SETTINGS["interaction_theta_3db_deg_values"]:
        for ks in SETTINGS["interaction_Ks_max_values"]:
            updates = {
                "beam.theta_3db_deg": theta,
                "payload.Ks_max": ks,
            }
            for n_users in SETTINGS["n_users_list"]:
                for seed in SETTINGS["seeds"]:
                    tasks.append({
                        "tag": "interaction:theta_x_Ksmax",
                        "x_name": "theta_x_Ksmax",
                        "x_value": f"theta={theta},Ks={ks}",
                        "theta_3db_deg": theta,
                        "Ks_max": ks,
                        "n_users": n_users,
                        "seed": seed,
                        "updates": updates,
                    })
    return tasks


# =============================================================================
# Aggregation
# =============================================================================

def _aggregate_stats(df: pd.DataFrame, group_cols: list[str], value_cols: list[str]) -> pd.DataFrame:
    rows = []
    for keys, g in df.groupby(group_cols, dropna=False):
        if not isinstance(keys, tuple):
            keys = (keys,)
        row = {c: v for c, v in zip(group_cols, keys)}
        for c in value_cols:
            vals = pd.to_numeric(g[c], errors="coerce").dropna()
            if len(vals) == 0:
                row[f"{c}_mean"] = float("nan")
                row[f"{c}_median"] = float("nan")
                row[f"{c}_std"] = float("nan")
                row[f"{c}_p10"] = float("nan")
                row[f"{c}_p90"] = float("nan")
                row[f"{c}_min"] = float("nan")
                row[f"{c}_max"] = float("nan")
                row[f"{c}_n"] = 0
            else:
                row[f"{c}_mean"] = float(vals.mean())
                row[f"{c}_median"] = float(vals.median())
                row[f"{c}_std"] = float(vals.std(ddof=0))
                row[f"{c}_p10"] = float(vals.quantile(0.10))
                row[f"{c}_p90"] = float(vals.quantile(0.90))
                row[f"{c}_min"] = float(vals.min())
                row[f"{c}_max"] = float(vals.max())
                row[f"{c}_n"] = int(len(vals))
        rows.append(row)
    return pd.DataFrame(rows)


# =============================================================================
# Tables / plotting helpers that read generated CSVs
# =============================================================================

def _read_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Expected CSV not found: {path}")
    return pd.read_csv(path)


def _write_tables_from_csvs(out_dir: Path) -> None:
    summary = _read_csv(out_dir / "sensitivity_summary.csv")
    interaction_summary = _read_csv(out_dir / "sensitivity_interaction_summary.csv")

    lines: list[str] = []
    lines.append("SENSITIVITY TABLES")
    lines.append("")
    lines.append("Aggregation note:")
    lines.append("- feasible rate uses the mean of the binary payload_feasible flag")
    lines.append("- continuous metrics should generally be interpreted through median and p10/p90")
    lines.append("")

    def add_table(title: str, df: pd.DataFrame):
        lines.append("=" * 120)
        lines.append(title)
        lines.append("")
        if df.empty:
            lines.append("(empty)")
            lines.append("")
            return
        lines.append(df.to_string(index=False))
        lines.append("")

    one_factor_cols = [
        "tag", "x_name", "x_value", "n_users",
        "payload_feasible_mean",
        "K_median", "U_mean_median", "U_max_median",
        "ent_edge_pct_median", "best_m_median",
        "payload_n_viol_T_median", "payload_T_over_sum_median",
        "runtime_total_s_median",
    ]
    one_factor_cols = [c for c in one_factor_cols if c in summary.columns]
    add_table("ONE-FACTOR SUMMARY", summary[one_factor_cols].copy() if not summary.empty else summary)

    inter_cols = [
        "tag", "n_users", "theta_3db_deg", "Ks_max",
        "payload_feasible_mean",
        "K_median", "U_mean_median", "U_max_median",
        "ent_edge_pct_median", "best_m_median",
        "runtime_total_s_median",
    ]
    inter_cols = [c for c in inter_cols if c in interaction_summary.columns]
    add_table("INTERACTION SUMMARY", interaction_summary[inter_cols].copy() if not interaction_summary.empty else interaction_summary)

    (out_dir / "sensitivity_tables.txt").write_text("\n".join(lines), encoding="utf-8")


def _to_numeric_sort_key(series: pd.Series) -> pd.Series:
    try:
        return pd.to_numeric(series)
    except Exception:
        return series.astype(str)


def _ordered_xlabels(g: pd.DataFrame) -> tuple[list[Any], dict[Any, int]]:
    tmp = g[["x_value"]].drop_duplicates().copy()
    tmp["_xsort"] = _to_numeric_sort_key(tmp["x_value"])
    tmp = tmp.sort_values("_xsort")
    labels = tmp["x_value"].tolist()
    pos_map = {v: i for i, v in enumerate(labels)}
    return labels, pos_map


def _plot_one_factor_metric(
    summary: pd.DataFrame,
    *,
    tag: str,
    metric_base: str,
    ylabel: str,
    out_dir: Path,
    use_mean: bool = False,
    y_log: bool = False,
) -> None:
    g = summary[summary["tag"] == tag].copy()
    if g.empty:
        return

    sweep_name = str(g["x_name"].iloc[0])
    labels, pos_map = _ordered_xlabels(g)

    if use_mean:
        center_col = f"{metric_base}_mean"
        low_col = None
        high_col = None
    else:
        center_col = f"{metric_base}_median"
        low_col = f"{metric_base}_p10"
        high_col = f"{metric_base}_p90"

    if center_col not in g.columns:
        return

    plt.figure(figsize=(7.2, 4.8))

    for n_users, gg in g.groupby("n_users"):
        gg = gg.copy()
        gg["_xsort"] = _to_numeric_sort_key(gg["x_value"])
        gg = gg.sort_values("_xsort")

        x = np.asarray([pos_map[v] for v in gg["x_value"]], dtype=float)
        y = pd.to_numeric(gg[center_col], errors="coerce").to_numpy(dtype=float)
        plt.plot(x, y, marker="o", label=f"n={int(n_users)}")

        if low_col is not None and high_col is not None and low_col in gg.columns and high_col in gg.columns:
            ylo = pd.to_numeric(gg[low_col], errors="coerce").to_numpy(dtype=float)
            yhi = pd.to_numeric(gg[high_col], errors="coerce").to_numpy(dtype=float)
            if np.isfinite(ylo).any() and np.isfinite(yhi).any():
                plt.fill_between(x, ylo, yhi, alpha=0.15)

    plt.xticks(range(len(labels)), [str(v) for v in labels])
    plt.xlabel(sweep_name)
    plt.ylabel(ylabel)
    if y_log:
        plt.yscale("log")
    plt.title(f"{ylabel} vs {sweep_name}")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    fname = f"{tag.replace(':','_')}_{metric_base}.png"
    plt.savefig(out_dir / fname, dpi=160)
    plt.close()


def _annotate_heatmap(ax, data: np.ndarray) -> None:
    if data.size == 0:
        return
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            v = data[i, j]
            if np.isfinite(v):
                if abs(v) >= 100 or float(v).is_integer():
                    txt = f"{v:.0f}"
                elif abs(v) >= 10:
                    txt = f"{v:.1f}"
                else:
                    txt = f"{v:.2f}"
                ax.text(j, i, txt, ha="center", va="center", fontsize=8)


ONE_FACTOR_PLOT_POLICY: dict[str, list[tuple[str, str, bool, bool]]] = {
    # metric_base, ylabel, use_mean, y_log
    "one_factor:theta_3db_deg": [
        ("payload_feasible", "Feasible rate", True, False),
        ("K", "K", False, False),
        ("U_mean", "U_mean", False, False),
        ("U_max", "U_max", False, False),
        ("ent_edge_pct", "Enterprise edge exposure (%)", False, False),
        ("best_m", "Minimum feasible prefix", False, False),
    ],
    "one_factor:elev_mask_deg": [
        ("payload_feasible", "Feasible rate", True, False),
        ("K", "K", False, False),
        ("U_mean", "U_mean", False, False),
        ("U_max", "U_max", False, False),
        ("best_m", "Minimum feasible prefix", False, False),
    ],
    "one_factor:Ks_max": [
        ("payload_feasible", "Feasible rate", True, False),
        ("K", "K", False, False),
        ("U_mean", "U_mean", False, False),
        ("best_m", "Minimum feasible prefix", False, False),
        ("payload_n_viol_K", "# violating sats (K)", False, False),
        ("payload_K_over_sum", "K overflow sum", False, False),
        ("runtime_total_s", "Runtime (s)", False, True),
    ],
    "one_factor:W_slots": [
        ("payload_feasible", "Feasible rate", True, False),
        ("K", "K", False, False),
        ("U_mean", "U_mean", False, False),
        ("U_max", "U_max", False, False),
        ("best_m", "Minimum feasible prefix", False, False),
        ("payload_n_viol_T", "# violating sats (T)", False, False),
        ("payload_T_over_sum", "T overflow sum", False, False),
        ("runtime_total_s", "Runtime (s)", False, True),
    ],
    "one_factor:rho_safe": [
        ("ent_edge_pct", "Enterprise edge exposure (%)", False, False),
        ("K", "K", False, False),
        ("U_mean", "U_mean", False, False),
    ],
    "one_factor:hotspot_scale": [
        ("payload_feasible", "Feasible rate", True, False),
        ("K", "K", False, False),
        ("U_mean", "U_mean", False, False),
        ("U_max", "U_max", False, False),
        ("ent_edge_pct", "Enterprise edge exposure (%)", False, False),
        ("best_m", "Minimum feasible prefix", False, False),
        ("runtime_total_s", "Runtime (s)", False, True),
    ],
    "one_factor:demand_mbps_median": [
        ("payload_feasible", "Feasible rate", True, False),
        ("K", "K", False, False),
        ("U_mean", "U_mean", False, False),
        ("U_max", "U_max", False, False),
        ("best_m", "Minimum feasible prefix", False, False),
        ("payload_n_viol_T", "# violating sats (T)", False, False),
        ("payload_T_over_sum", "T overflow sum", False, False),
        ("runtime_total_s", "Runtime (s)", False, True),
    ],
    "one_factor:demand_mbps_median_stress": [
        ("payload_feasible", "Feasible rate", True, False),
        ("K", "K", False, False),
        ("U_mean", "U_mean", False, False),
        ("U_max", "U_max", False, False),
        ("best_m", "Minimum feasible prefix", False, False),
        ("payload_n_viol_T", "# violating sats (T)", False, False),
        ("payload_T_over_sum", "T overflow sum", False, False),
        ("runtime_total_s", "Runtime (s)", False, True),
    ],
}


def _plot_one_factor_from_csvs(out_dir: Path) -> None:
    summary = _read_csv(out_dir / "sensitivity_summary.csv")
    if summary.empty:
        return

    for tag, specs in ONE_FACTOR_PLOT_POLICY.items():
        g = summary[summary["tag"] == tag]
        if g.empty:
            continue
        for metric_base, ylabel, use_mean, y_log in specs:
            _plot_one_factor_metric(
                summary,
                tag=tag,
                metric_base=metric_base,
                ylabel=ylabel,
                out_dir=out_dir,
                use_mean=use_mean,
                y_log=y_log,
            )


def _plot_interaction_from_csvs(out_dir: Path) -> None:
    interaction_summary = _read_csv(out_dir / "sensitivity_interaction_summary.csv")
    if interaction_summary.empty:
        return

    metric_specs = [
        ("payload_feasible_mean", "Feasible rate"),
        ("K_median", "K"),
        ("U_mean_median", "U_mean"),
        ("U_max_median", "U_max"),
        ("ent_edge_pct_median", "Enterprise edge exposure (%)"),
        ("best_m_median", "Minimum feasible prefix"),
        ("runtime_total_s_median", "Runtime (s)"),
    ]

    for n_users, g in interaction_summary.groupby("n_users"):
        g = g.copy()
        g["theta_3db_deg"] = pd.to_numeric(g["theta_3db_deg"], errors="coerce")
        g["Ks_max"] = pd.to_numeric(g["Ks_max"], errors="coerce")
        g = g.sort_values(["theta_3db_deg", "Ks_max"])

        for metric, title_metric in metric_specs:
            if metric not in g.columns:
                continue
            pivot = g.pivot(index="theta_3db_deg", columns="Ks_max", values=metric)
            if pivot.empty:
                continue

            fig, ax = plt.subplots(figsize=(6.2, 5.0))
            im = ax.imshow(pivot.values, aspect="auto", origin="lower")
            ax.set_xticks(range(len(pivot.columns)))
            ax.set_xticklabels([str(int(c)) if float(c).is_integer() else str(c) for c in pivot.columns])
            ax.set_yticks(range(len(pivot.index)))
            ax.set_yticklabels([str(v) for v in pivot.index])
            ax.set_xlabel("Ks_max")
            ax.set_ylabel("theta_3db_deg")
            ax.set_title(f"{title_metric}, n_users={int(n_users)}")
            fig.colorbar(im, ax=ax)
            _annotate_heatmap(ax, pivot.values)
            plt.tight_layout()
            plt.savefig(out_dir / f"interaction_theta_x_Ksmax_{metric}_n{int(n_users)}.png", dpi=160)
            plt.close()


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    out_dir = Path(str(SETTINGS["out_dir"]))
    out_dir.mkdir(parents=True, exist_ok=True)

    # One-factor sweeps
    one_factor_tasks = _build_one_factor_tasks()
    one_factor_results = _run_tasks(one_factor_tasks)
    df_runs = pd.DataFrame(one_factor_results)
    df_runs.to_csv(out_dir / "sensitivity_runs.csv", index=False)

    value_cols = [
        "ok",
        "payload_feasible",
        "K",
        "U_mean",
        "U_max",
        "ent_edge_pct",
        "best_m",
        "ms_n_active",
        "payload_n_viol_K",
        "payload_n_viol_T",
        "payload_K_over_sum",
        "payload_T_over_sum",
        "runtime_total_s",
    ]
    summary = _aggregate_stats(df_runs, ["tag", "x_name", "x_value", "n_users"], value_cols)
    summary.to_csv(out_dir / "sensitivity_summary.csv", index=False)

    # Interaction sweep
    interaction_tasks = _build_interaction_tasks()
    interaction_results = _run_tasks(interaction_tasks)
    df_inter = pd.DataFrame(interaction_results)
    df_inter.to_csv(out_dir / "sensitivity_interaction_runs.csv", index=False)

    required_cols = ["tag", "n_users", "theta_3db_deg", "Ks_max"]
    missing = [c for c in required_cols if c not in df_inter.columns]
    if missing:
        raise RuntimeError(
            f"Interaction DataFrame is missing required columns: {missing}. "
            f"Available columns: {list(df_inter.columns)}"
        )

    interaction_summary = _aggregate_stats(
        df_inter,
        ["tag", "n_users", "theta_3db_deg", "Ks_max"],
        value_cols,
    )
    interaction_summary.to_csv(out_dir / "sensitivity_interaction_summary.csv", index=False)

    # IMPORTANT: read back generated CSVs for tables and plots
    _write_tables_from_csvs(out_dir)
    _plot_one_factor_from_csvs(out_dir)
    _plot_interaction_from_csvs(out_dir)

    print(f"[done] wrote sensitivity outputs to: {out_dir.resolve()}")


if __name__ == "__main__":
    main()